### ISSUE TITLE
Date and read-time present in table of contents but missing from post 

### ISSUE THREAD

**Issue by colin-bledsoe** [thegeeklab/hugo-geekblog#11]
The example Geekblog site includes the upload date and approximate article duration metadata in both the table of contents view  (in the footer) and the post view (in the header). 

My implementation of Geekblog is only showing this metadata on the table of contents and not in the gblog-post__header div which is missing a nested gblog-post__meta div. 

Can you help me understand how I can include this metadata on the post itself?

**Desired behavior -**
![Geekblog_Example](https://user-images.githubusercontent.com/15932109/100391701-86cae600-2ff1-11eb-8bc7-6d49c8379a28.png)

**My implementation -**
![My_Implementation](https://user-images.githubusercontent.com/15932109/100391582-20de5e80-2ff1-11eb-9cf5-31062379a9fb.png)

**Comment by xoxys** [comment]
Thanks for your report. Can you show me how your `content` folder looks like?

**Comment by colin-bledsoe** [comment]
This is my content folder:
![image](https://user-images.githubusercontent.com/15932109/100392897-3eadc280-2ff5-11eb-9653-da80ef8f7bfa.png)

**Comment by colin-bledsoe** [comment]
So I just changed that folder name from "post" to "posts" and that appears to have resolved the issue!

**Comment by xoxys** [comment]
Ok you have to keep it named `posts`  for now as this is hard-coded, see https://github.com/thegeeklab/hugo-geekblog/blob/master/layouts/_default/single.html

**Comment by colin-bledsoe** [comment]
Thanks for the quick reply! The theme is fantastic and exactly what I was looking for.

**Comment by xoxys** [comment]
Right. I'll check how to fix it in a future release, so keep this issue open to track it. Thanks again :)

**Comment by xoxys** [comment]
This should be fixed now.
