### ISSUE TITLE
Markdown Header Authors Functionality Issue

### ISSUE THREAD

**Issue by colin-bledsoe** [thegeeklab/hugo-geekblog#12]
I am having an issue when trying to build after using the authors tag in the markdown header. I included the markdown header and the corresponding error. If I exclude the authors tag altogether I can build without problems.

This is not a critical feature because I will be the sole contributor on my blog but thought the feedback might be nice to have.

---
title: "Getting Started"
date: 2020-11-26T08:09:49-07:00
draft: true
authors:
    - colinbledsoe
tags:
    - Documentation
---

`C:\Hugo\Sites\colinbledsoe>hugo server -D
Start building sites …
ERROR 2020/11/26 14:57:05 render of "page" failed: execute of template failed: template: _default/single.html:5:7: executing "_default/single.html" at <partial "head/meta" .>: error calling partial: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\partials\head\meta.html:18:26": execute of template failed: template: partials/head/meta.html:18:26: executing "partials/head/meta.html" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "term" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "home" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "term" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
Built in 99 ms
Error: Error building site: failed to render pages: render of "section" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil`

**Comment by xoxys** [comment]
Thanks. To use the authors parameter you have to create a corresponding data file, see https://github.com/thegeeklab/hugo-geekblog/blob/master/exampleSite/data/authors/john-doe.yml.

So in your example it should look like this:

```
content/
data/authors/colinbledsoe.yml
```

**Comment by colin-bledsoe** [comment]
Thanks! Now the build is successful, but I'm still not getting the author icon in the footer on the table of contents.

**Comment by xoxys** [comment]
Could you post your page config.yaml/toml please?

**Comment by colin-bledsoe** [comment]
```
baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "ColinBledsoe"
theme = "hugo-geekblog"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
#enableGitInfo = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
    
[taxonomies]
  author = "authors"
  tag = "tags"
  series = "series"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
    name = "Atom"
    mediaType = "application/atom+xml"
    # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
    baseName = "atom"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

  [outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]

  # (Optional, default none) Sites main author.
  geekblogAuthor = "colinbledsoe"
```

**Comment by xoxys** [comment]
Is your `data/authors/colinbledsoe.yml` file empty?

**Comment by colin-bledsoe** [comment]
No it isn't empty, inside data/authors/colinbledsoe.yml is:

name: Colin Bledsoe
email: my_email@example.com

**Comment by xoxys** [comment]
Hmm, I'm currently unable to reproduce it. The only way I was able to reproduce is with an empty data file.

**Comment by xoxys** [comment]
Is the full source of your site somewhere public available, so I could take a look or debug?

**Comment by colin-bledsoe** [comment]
Yes I just published the site to my public github repository [https://github.com/colin-bledsoe/colinbledsoe](url). I'm also trying to troubleshoot but have come up empty-handed thus far.

**Comment by xoxys** [comment]
Now I'm completely confused. How have you installed the theme in your repo? Because assets like the default CSS files (e.g. main.min.css) are missing.

**Comment by colin-bledsoe** [comment]
I'm sorry, I dumped all the files in at once when I uploaded it. For some reason it looks like not all the files were uploaded those CSS files are missing, I'll add them now.

**Comment by colin-bledsoe** [comment]
With the exception of  .jsbeautifyrc, .prettierignore, and .prettierrc which I had issues uploading to my repository, the missing .CSS files are now in the repo.

**Comment by xoxys** [comment]
No worries, we will get it sorted :) I think I found the issue, let me test it a bit more, then I'll publish a fix. I'll also exclude the dot files from the next release.

**Comment by colin-bledsoe** [comment]
Ok sounds good, thank you!

**Comment by colin-bledsoe** [comment]
The latest commit was successful in resolving the issue!

**Comment by xoxys** [comment]
Cool. New release v0.7.0 is also ready. So this issue can be closed?

**Comment by colin-bledsoe** [comment]
Yep this issue can be closed

**Comment by xoxys** [comment]
Thanks again
