### ISSUE TITLE
all dark mode buttons displayed in safari iOS

### ISSUE THREAD

**Issue by wedaly** [thegeeklab/hugo-geekblog#123]
hi there! I just installed the theme on my blog, and it's been working great so far. While testing, I noticed a small issue on iOS Safari:

**steps to reproduce**: open [https://hugo-geekblog.geekdocs.de/](https://hugo-geekblog.geekdocs.de/) in Safari iOS.  I used iOS version 15.1.1, iPhone 12.
**expected behavior**: single button is displayed for dark mode, tapping it toggles between auto/light/dark mode
**actual behavior**: all three buttons are displayed (see screenshot below), and tapping them appears to do nothing.

This is working perfectly on Safari on my macbook air (big sur). I'm only able to reproduce the issue on iOS.

**screenshot**:
![3E44C26B-AD28-4B27-8819-E7A72C5DB62A](https://user-images.githubusercontent.com/2948394/146310043-0496ca44-5a1d-4ce1-9dbe-d07b2edef6d0.PNG)

**Comment by xoxys** [comment]
Hi, thanks for your well written report! Sadly, I have no iOS device and I need to check to debug/reproduce it on my side as right now I'm not able to reproduce it on any other mobile browser :(

**Comment by wedaly** [comment]
If anyone else runs into this, I worked around the issue in my blog by removing the dark mode buttons:

1. `cp themes/hugo-geekblog/layouts/partials/site-header.html layouts/partials/`
2. edit `layouts/partials/site-header.html` like this:
```
<span id="gblog-dark-mode">
  <!-- remove dark mode buttons because of iOS Safari display issues -->
</span>
```
(I kept the parent span since otherwise the JS code throws an error).

**Comment by xoxys** [comment]
Im really sorry about this issue.

**Comment by xoxys** [comment]
Hmm, I've tested Browserstack now, but I'm not able to reproduce it so far -.-

![image](https://user-images.githubusercontent.com/3391958/146515221-8ff3acd1-8895-4113-981b-a0b354701a1c.png)

**Comment by wedaly** [comment]
I wonder if maybe it's a regression in iOS Safari itself. I originally reproduced this on iOS15.1.1. This morning I tried upgrading to 15.2 but am still seeing the issue. Every other system I've tested works as expected (Firefox on Fedora 35, Chrome on macOS, Safari on macOS Big Sur, and Edge on Windows 11)

**Comment by kulmann** [comment]
Hey, didn't look into it much, but can't reproduce it on my iOS Safari either (iPhone 12, iOS 15.1 and 15.2). Also tried it on an iPad mini 5 with iOS 14.8 and 15.2, not happening.

@wedaly is it an option for you to re-introduce the buttons to your site, to double check there again with some iOS devices?

**Comment by wedaly** [comment]
@kulmann thanks again for looking into it. I'm still able to reproduce the issue on the demo site [https://hugo-geekblog.geekdocs.de/](https://hugo-geekblog.geekdocs.de/) on my iPhone 12 iOS 15.2.

It seems to be working correctly on an iPad with iOS 15.1. I'll try to find some other folks to test it on their devices too.

I connected my iPhone to a macbook so I could use Safari dev tools, and I'm seeing this message: "Security Error: The operation is insecure" occurring in [darkmode-f8af5df16d.min.js](https://hugo-geekblog.geekdocs.de/js/darkmode-f8af5df16d.min.js) line 11 (applyTheme).  Here are some screenshots:

<img width="1205" alt="security-error-screenshot" src="https://user-images.githubusercontent.com/2948394/146618777-9c48f2b2-4a9b-4829-a961-abb1c11aa27d.png">
<img width="1205" alt="security-error-screenshot-2" src="https://user-images.githubusercontent.com/2948394/146618785-55844332-8c89-4056-bbc1-9381d8a045df.png">

At one point the iPhone had some corporate security software installed, so maybe that set a flag somewhere that's triggering the error.

**Comment by wedaly** [comment]
I asked someone else to try to reproduce it on her iPhone iOS 15.1.1, and it's working correctly there too. Feeling pretty confident that this is an issue with my phone, not the blog theme. Apologies for the false alarm, and thanks again for taking the time to investigate!

**Comment by wedaly** [comment]
okay, I figured out that disabling "Block All Cookies" fixes the issue on my phone! I guess Safari also blocks local storage access when that's enabled?

**Comment by xoxys** [comment]
Interesting. Maybe we can add a check if the local storage is available or not and hide all buttons if not. But Im not sure why all three buttons were displayed when the local storage is not acessable :thinking:

**Comment by xoxys** [comment]
This blog post seems to outline the issue a bit more: https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/ I'll re-open the issue and would like to take a closer look.

**Comment by xoxys** [comment]
Yeah, I'm definitely able to reproduce it in FF now with disabled local storage. Thanks again for the hint in this direction!

![image](https://user-images.githubusercontent.com/3391958/147114734-8eb29151-06e8-4eb0-b85d-7b4f1c95498f.png)

![image](https://user-images.githubusercontent.com/3391958/147114796-da617afe-7b18-4701-93d6-4779e706d09b.png)
