### ISSUE TITLE
Create taxonomy list page

### ISSUE THREAD

**Issue by xoxys** [thegeeklab/hugo-geekblog#169]
Hi,

Yes a page that links to the tags page. I have this setting enabled  geekblogTagsToMenu = false. I want a static navigation menu and a separate page for the tags. I have too many tags for the bar to work for me.

Regards

_Originally posted by @Xhanti in https://github.com/thegeeklab/hugo-geekblog/discussions/167#discussioncomment-2065547_

**Comment by xoxys** [comment]
![image](https://user-images.githubusercontent.com/3391958/151659118-7ec36816-1cdb-4107-ad17-1052dc7a615c.png)

@Xhanti Let me know what you think

**Comment by Xhanti** [comment]
@xoxys looks great! Thank you for the quick turnaround time

**Comment by xoxys** [comment]
Happy to help :) Merged and release tagged. Should be available in a few minutes.

**Comment by Xhanti** [comment]
Thanks again 🙏🏾
