### ISSUE TITLE
How do I change the favicon?

### ISSUE THREAD

**Issue by rsmarples** [thegeeklab/hugo-geekblog#21]
Overriding the site.webmanifest in static doesn't seem to affect the build.
Putting the image in the params section only references it in the meta data, doens't actually replace the icon?

**Comment by xoxys** [comment]
Thanks for your report. I'm a bit confused :) by default, the theme includes only three basic favicons/formats, see https://github.com/thegeeklab/hugo-geekblog/blob/master/layouts/partials/head/favicons.html. 

If you want to extend it you have to overwrite and extend the `partials/head/favicons.html` in your project’s root e.g. as I do on my own blog see https://gitea.rknet.org/xoxys/thegeeklab/src/branch/master/layouts/partials/head/favicons.html and https://gohugobrasil.netlify.app/themes/customizing/#override-template-files

If you also want to replace the default icons you can provide your own files in `static/favicon/` in your project’s root, see

**Comment by rsmarples** [comment]
Ah I see now, thanks.

Good to now the small partials can be replaced by top level statics.
